weights: yolov5n.pt
cfg: /content/gdrive/MyDrive/yolov5n/yolov5/models/yolov5n.yaml
data: /content/gdrive/MyDrive/yolov5n/yolov5/data/mydata.yaml
hyp: yolov5/data/hyps/hyp.scratch-low.yaml
epochs: 100
batch_size: 32
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: '0'
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: yolov5/runs/train
name: yolov5n_results
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: yolov5/runs/train/yolov5n_results11
